#


FROM rockylinux:latest


RUN yum -y install gzip
RUN gzip -cd haproxy-1.5.11.tar.gz | tar vxf -
RUN cd haproxy-1.5.11 

CMD /usr/bin/supervisord -c /etc/supervisord.conf

#CMD haproxy -f /etc/haproxy/haproxy.cfg





